### ISSUE TITLE
Planned any release?

### ISSUE THREAD

**Issue by bvis** [chartinger/behat-twig-report-extension#4]
Hi, have you planned any initial release of your component?
It's very useful to have a tag with the reference to use it in composer projects.

**Comment by mithikos** [comment]
Hi, I have also make a small change on the code. It will use the name of the suite for the template.
Will be nice if I can commit it. :)

**Comment by mithikos** [comment]
Hi,

I have include also error details for each step that have bee failed. Any chance to push my changes ?

**Comment by chartinger** [comment]
@mithikos just create a [pull request](https://help.github.com/articles/using-pull-requests/)
@bvis i will look into it

**Comment by mithikos** [comment]
Pull request has been created!

**Comment by loostro** [comment]
Please add any tag. Something like `0.1.0` (if you believe this is not yet stable) would be enough. Cheers :)

**Comment by chartinger** [comment]
I added the v0.1.0 tag.
Just wanted to note that current development of this extension is part of another project and it will take a while before these changes are pushed into this repository. (due to limited time)
