### ISSUE TITLE
Add embed screen to report

### ISSUE THREAD

**Issue by narozhniyy** [chartinger/behat-twig-report-extension#7]
Hi guys, I wanted add screenshot to report and add your code (The facility exists to embed a screenshot into test failures.). And I have some questions to you:
What about takeScreenshot() method? I didn't find this method in your source, if it's should be my method how I can add already exists screenshot to your Twig report?

**Comment by chartinger** [comment]
Behat is just a test runner, so it does not know if you even test something with an visual output and neither does this extension. That said, my guess is you use it in combination with Mink and installed a hook on failing tests which capture the screen.

One possibility would be saving the screenshots and just add an img tag with the relative url in a custom twig file if the scenario failed. Only tricky thing is to name the screenshots in a way you can re-construct in twig with the given information. (eg name of the suite+scenario)

Currently there is no native support for mink screenshots or an easy way to extend the core functionality i am afraid, but it should not be too hard.
