### ISSUE TITLE
Support for behat with version > 3.0?

### ISSUE THREAD

**Issue by thubuiTMA** [chartinger/behat-twig-report-extension#8]
Hi, 
I have used behat with version 3.1.0, and I need to install the extension for my project. As I see, the extension only supports with behat ~3.0.0 (under 3.1.0). So, can you please update the extension, so that I can use it with behat 3.1.0?

Thanks

**Comment by chartinger** [comment]
Sadly, I do not have the time to maintain this project. Please check out 
https://github.com/dutchiexl/BehatHtmlFormatterPlugin

Sorry for the inconvenience
